// <auto-generated />
namespace CodeFirst_Invoice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class OriginalDB21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OriginalDB21));
        
        string IMigrationMetadata.Id
        {
            get { return "201903250835084_OriginalDB21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
